version: '3.9'
services:
  db_backend:
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_USER=${PGUSER}
      - POSTGRES_PASSWORD=${PGPASSWORD}
      - POSTGRES_DB=${PGDATABASE}
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "${PGPORT}:5432"
    networks:
      - server-network
    healthcheck:
      test: ["CMD-SHELL", "/app/healthcheck.sh"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "${SERVER_PORT}:4000"
    environment:
      - DATABASE_URL=postgres://app_user:app_password@db_backend:5432/app_db
    depends_on:
      - db_backend
    networks:
        - server-network
    volumes: # Añade esta sección
      - ./server:/app # Monta el directorio 'server' en el contenedor en la ruta '/app'
      - /app/node_modules # Excluye el directorio 'node_modules'

volumes:
  pgdata:

networks:
  server-network: